formalibre_pia_controller:
    resource: "@FormaLibrePiaBundle/Controller/PiaController.php"
    type:     annotation

formalibre_pia_tache_controller:
    resource: "@FormaLibrePiaBundle/Controller/PiaTacheController.php"
    type:     annotation

formalibre_pia_action_controller:
    resource: "@FormaLibrePiaBundle/Controller/PiaActionController.php"
    type:     annotation
